### ISSUE TITLE
Kubernetes Type ServiceAccount not authenticating

### ISSUE THREAD

**Issue by dgdarlington** [microsoft/terraform-provider-azuredevops#120]
### Terraform (and Azure DevOps Provider) Version

Terraform: "0.12.29"
Azure DevOps Provider: ">= 0.0.1"

### Terraform Configuration Files

```hcl
data "azuredevops_project" "it-project" {
  project_name = "IT"
}

provider "azuredevops" {
  version = ">= 0.0.1"
  org_service_url = "https://dev.azure.com/blah/"
  # AZDO_PERSONAL_ACCESS_TOKEN needed
}

data "kubernetes_service_account" "d" {
  metadata {
    name = "ado-devops-k8s-dev-v1-service-account"
    namespace = "kube-system"
  }
}

data "kubernetes_secret" "deployment_secret" {
  metadata {
    name      = data.kubernetes_service_account.d.default_secret_name
    namespace = data.kubernetes_service_account.d.metadata[0].namespace
  }
}

resource "azuredevops_serviceendpoint_kubernetes" "se_service_account" {
  project_id            = data.azuredevops_project.it-project.id
  service_endpoint_name = "K8s-test-devops-service-connection"
  apiserver_url         = "https://blah.hcp.eastus2.azmk8s.io:443"
  authorization_type    = "ServiceAccount"
  description           = "Managed by Terraform - Created during cluster provisioning - Grants access to devops cluster"

  service_account {
    token   = data.kubernetes_secret.deployment_secret.data.token
    ca_cert = data.kubernetes_secret.deployment_secret.data["ca.crt"]
  }
}
```
The service connection gets created without error, but I run a pipeline trying to use this service connection and get:
```
##[error]error: error loading config file "/home/vsts/work/_temp/kubectlTask/1596224340999/config": yaml: control characters are not allowed
```
### Steps to Reproduce

1. `terraform apply` # code from above
2. Run pipeline

```
steps:
  - task: KubernetesManifest@0
    displayName: Deploy
    inputs:
      kubernetesServiceConnection: K8s-test-devops-service-connection #K8s-devops-k8s-dev-v1-service-connection
      namespace: default
      manifests: dev/azdo-terraform-test/service.yml
```
