### ISSUE TITLE
Provider cannot read secure environment variable AZDO_PERSONAL_ACCESS_TOKEN

### ISSUE THREAD

**Issue by cd83** [microsoft/terraform-provider-azuredevops#183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.29

azuredevops v0.0.1

### Affected Resource(s)

* `provider "azuredevops"`

### Terraform Configuration Files

```hcl
AZDO_PERSONAL_ACCESS_TOKEN=<redacted>

provider "azuredevops" {
  version         = ">= 0.0.1"
  org_service_url = "https://dev.azure.com/<redacted>/"
}
```

### Expected Behavior

When AZDO_PERSONAL_ACCESS_TOKEN is not a secure environment variable, everything works. Expected behavior for when AZDO_PERSONAL_ACCESS_TOKEN is a secure variable is that everything should still work.

### Actual Behavior

`Error: the personal access token is required`

### Steps to Reproduce

1. Set AZDO_PERSONAL_ACCESS_TOKEN as a secure environment variable
1. `terraform init`
1. `terraform plan`

**Comment by xuzhang3** [comment]
@cd83 Where `AZDO_PERSONAL_ACCESS_TOKEN` you configured? For pipelines, the secret should be able to read ,we also used in this way for test cases.

**Comment by cd83** [comment]
It is being set in our Pipeline Variable (which in turn sets it as an Environment variable on the agent).

It works when it is **not secure**, but when we click the lock to `Change variable type to secret` it is unable to be read.

![image](https://user-images.githubusercontent.com/12536689/92937981-9fbff400-f411-11ea-9dc6-ce76389b0de4.png)

**Comment by xuzhang3** [comment]
HI @cd83     Secret variables are not automatically decrypted in YAML pipelines and need to be passed to your YAML file with env: or a variable at the root level.  [Pipeline secret variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#user-defined-variables)

Usage example:
![image](https://user-images.githubusercontent.com/57888764/93051283-ce023580-f696-11ea-81d6-67eda2c91448.png)

**Comment by cd83** [comment]
This pipeline was created in the UI (using the "Classic Editor") and not via YAML. (It is on our to-do list to convert it). We have worked with secret variables in other pipelines that were created via YAML. This seems to be an issue affecting the UI / Classic Editor pipelines.

Here is a screenshot of the Variables tab in the UI pipeline:

![image](https://user-images.githubusercontent.com/12536689/93100359-adbe8080-f66e-11ea-8293-c7f9ad976590.png)

**Comment by xuzhang3** [comment]
@cd83  Same like YAML,  classis editor need  export the values to **Environment** too.  [Set secret variables
](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#secret-variables)
![image](https://user-images.githubusercontent.com/57888764/93159510-e890e900-f740-11ea-9d95-a8fd257db34e.png)

**Comment by cd83** [comment]
The Task we are using does not provide an option to input Environment Variables as shown in your screenshot, and as I can see is available in Tasks such as the Powershell or Azure Powershell Tasks.

Link to the Task we are using: https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1/README.md

Here is a screenshot of the options we have available in the Task we are using:

![image](https://user-images.githubusercontent.com/12536689/93232991-25a8ab80-f740-11ea-8d42-d423b21e817b.png)

I have tried creating a Powershell Task to take the secure AZDO_PERSONAL_ACCESS_TOKEN pipeline variable and export the value as an Environment variable (just as a test, would not want to use in production), but this did not work either:

![image](https://user-images.githubusercontent.com/12536689/93233209-6ef8fb00-f740-11ea-8498-e478f7e2ac27.png)

**Comment by xuzhang3** [comment]
@cd83 Sorry, cannot help  you here.

**Comment by cd83** [comment]
How are you running your Terraform in Azure DevOps? Can you share an example of the tasks that you are using?

We are using the official Terraform Task from Microsoft - what are you using?

**Comment by xuzhang3** [comment]
@cd83   We use yaml and bash script.  Pipeline Terraform extension is also OK. 
A simple YAML script. 
```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- bash: |
    wget https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
    echo "Unzip Terraform archive"
    unzip terraform_0.12.29_linux_amd64.zip

    echo 'Check Terrform version'
    ./terraform --version
  displayName: 'Terraform install'  

- bash: |
    echo 'Terraform init...'
    ./terraform init
    
    echo 'Terraform plan...'
    ./terraform plan
    
    echo 'Terraform apply...'
    ./terraform apply --auto-approve=true

    echo 'Terraform destroy...'
    ./terraform destroy --auto-approve=true
  displayName: 'Terraform Script Execute'
  env:
      AZDO_PERSONAL_ACCESS_TOKEN: $(AZDO_PERSONAL_ACCESS_TOKEN)

```
