### ISSUE TITLE
Schedule triggers not working with github repo while creating azure devops pipeline using terraform script

### ISSUE THREAD

**Issue by dikal795** [microsoft/terraform-provider-azuredevops#362]
We have a yaml file in github with schedule job added in it as below 
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
schedules:
```yaml
- cron: "*/1 * * * 1-5"
  displayName: Daily midnight build
  branches:
    include:
    - main
    - test
  always: true

trigger: none
pr: none

pool:
  name: 'build'

steps:
- script: echo Hello, world!!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
```
**Using below terraform script to create pipeline in azure devops** 
```hcl
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = "0.1.3"
    }
  }
}
provider "azuredevops" {
  org_service_url       = "https://dev.azure.com/orgname"
  personal_access_token = ""
}

resource "azuredevops_build_definition" "pipeline11" {

  project_id = ""
  name       = "testterraform"

  ci_trigger {
    use_yaml = true
  }

  pull_request_trigger {
    use_yaml       = true
    initial_branch = "main"
    forks {
      enabled       = false
      share_secrets = false
    }
  }

  repository {
    repo_type             = "GitHub"
    repo_id               = ""
    branch_name           = "main"
    service_connection_id = "
    yml_path              = "azure-pipelines.yml"
  }

}
```
Schedule jobs should trigger every one min but this is not happening . Is there any thing we missed to add in terraform script?
