### ISSUE TITLE
[New Functionality] Allow build definition authorization to repository

### ISSUE THREAD

**Issue by straubt1** [microsoft/terraform-provider-azuredevops#7]
### Description

Currently the resource `azuredevops_resource_authorization` only supports service endpoints.

Feature request for adding build definition authorization to a repository.

If you are extending a build pipeline from one repository to another, ADO will prompt you to permit access the first time it is run

### New or Affected Resource(s)

* azuredevops_resource_authorization

### Potential Terraform Configuration

azuredevops_resource_authorization

```hcl
resource "azuredevops_resource_authorization" "pipeline_auth" {
  project_id  = azuredevops_project.project.id
  resource_id = azuredevops_build_definition.plan.id
  authorized  = true
}
```

### References

* [resource_authorization](https://www.terraform.io/docs/providers/azuredevops/r/resource_authorization.html)

<img width="989" alt="image" src="https://user-images.githubusercontent.com/8408833/85229676-cb9e8100-b3b0-11ea-8a90-65d4f4e36aa7.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by EliiseS** [comment]
@straubt1 "If you are extending a build pipeline from one repository to another," Could you specify what you mean by that? I'm trying to repro the "This pipeline needs permissions to access a resource before this can continue to run"

**Comment by straubt1** [comment]
Here is an example.

I have a file `pipeline/tfe-run-template.yml` in repository `terraform-pipeline`.

Then in repository 'terraform-code', I reference that pipeline file with the `extends` option: 

```
trigger: none
pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: terraform-pipeline
      type: Git
      name: terraform-tfe-ado/terraform-pipeline
      ref: master

variables:
  - group: "TFE Variable Group"

pool:
  vmImage: "ubuntu-latest"

extends:
  template: pipeline/tfe-run-template.yml@terraform-pipeline
  parameters:
    isSpeculativePlan: True
```

This results in the permissions request (see above screenshot).
