### ISSUE TITLE
Can't link Azure DevOps Group to Azure AD (Microsoft Entra) Group with service accounts.

### ISSUE THREAD

**Issue by wi5nia** [microsoft/terraform-provider-azuredevops#896]
Hi,

I am trying to write some code which will link and ADO Group to an AAD Group. When we run this code locally when being logged with an user who is in the _Project Collection Administrators_ group and also a Global Admin of the tenant to which the ADO organisation is connected all is working just fine.

When I move my code and execution to ADO it starts to fail with this error.

```
2023-10-10T12:11:51.690Z [ERROR] provider.terraform-provider-azuredevops_v0.9.1: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_severity=ERROR diagnostic_summary="REST call returned status code 503" tf_proto_version=5.3 tf_req_id=9e182511-ea55-d17d-45f6-1616b7f64546 tf_resource_type=azuredevops_group @module=sdk.proto diagnostic_detail= tf_provider_addr=registry.terraform.io/microsoft/azuredevops tf_rpc=ApplyResourceChange timestamp=2023-10-10T12:11:51.689Z
2023-10-10T12:11:51.691Z [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-10-10T12:11:51.691Z [ERROR] vertex "azuredevops_group.link" error: REST call returned status code 503
╷
│ Error: REST call returned status code 503
│ 
│   with azuredevops_group.link,
│   on main.tf line 54, in resource "azuredevops_group" "link":
│   54: resource "azuredevops_group" "link" {
│ 
╵
```

Here is the Terraform code

```hcl
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
    }
    azuread = {
      source = "hashicorp/azuread"
    }
  }
}

variable "AZDO_PERSONAL_ACCESS_TOKEN" {
  type = string
}

variable "ARM_TENANT_ID" {
  type = string
}

variable "ARM_CLIENT_ID" {
  type = string
}

variable "ARM_OIDC_TOKEN" {
  type = string
}

provider "azuredevops" {
  org_service_url       = "https://dev.azure.com/{my_org_name}"
  personal_access_token = var.AZDO_PERSONAL_ACCESS_TOKEN
}

provider "azuread" {
  tenant_id = var.ARM_TENANT_ID
  client_id = var.ARM_CLIENT_ID
  oidc_token = var.ARM_OIDC_TOKEN
}

resource "azuredevops_project" "example" {
  name = "ADOAADTest"
}

resource "azuredevops_group" "somegroup" {
    scope = azuredevops_project.example.id
    display_name = "test"
    description = "Some description"
}

resource "azuread_group" "aad_group" {
  display_name = "test"
  security_enabled = true
}

resource "azuredevops_group" "link" {
    origin_id = azuread_group.aad_group.object_id
}

resource "azuredevops_group_membership" "membership" {
    group = azuredevops_group.somegroup.descriptor
    members = [
        azuredevops_group.link.descriptor
    ]
}
```

And here is the ADO pipeline code

```yaml
pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - main

workspace:
  clean: outputs | resources | all

steps:
  - download: none

  - checkout: self
    persistCredentials: true
    
  - task: AzureCLI@2
    displayName: 'Prepare Credentials for Terraform Backend State'
    inputs:
      addSpnToEnvironment: true
      azureSubscription: 'spnname'
      scriptLocation: 'inlineScript'
      scriptType: 'bash'
      inlineScript: |
        set -euo pipefail
        echo "##vso[task.setvariable variable=TF_VAR_ARM_TENANT_ID;issecret=false]${tenantId}"
        echo "##vso[task.setvariable variable=TF_VAR_ARM_CLIENT_ID;issecret=false]${servicePrincipalId}"
        echo "##vso[task.setvariable variable=TF_VAR_ARM_OIDC_TOKEN;issecret=false]${idToken}"

  - task: TerraformInstaller@0   
    displayName: "Install Terraform"   
    inputs:     
      terraformVersion: '1.5.6'     
      terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'
  
  - script: |
      terraform init \
      && terraform apply --auto-approve
    displayName: 'Terraform Apply for test Environment'
    env:
      TF_LOG: DEBUG
      ARM_USE_OIDC: true
      TF_VAR_AZDO_PERSONAL_ACCESS_TOKEN: $(System.AccessToken)
```

The project build account is part of the Project Collection Service Accounts group
<img width="1503" alt="image" src="https://github.com/microsoft/terraform-provider-azuredevops/assets/12593852/720524c1-18c7-46bd-97a0-d6d71ac4193c">

Which is a part of the Project Collection Administrators group
<img width="1505" alt="image" src="https://github.com/microsoft/terraform-provider-azuredevops/assets/12593852/a6a2807c-e235-455d-a204-00ba0b595b0d">

The SPN which is used for the deployment has those permissions and we are using federated identity
<img width="1018" alt="image" src="https://github.com/microsoft/terraform-provider-azuredevops/assets/12593852/ba38a255-54fd-4a75-bdce-806a285e6cf4">

Any ideas what could be the issue?
